export const carCard = {
  title: 'CR-V',
  vehicleType: 'SUV',
  gallons: '80',
  image: '/img/car.png',
  transmission: 'Manual',
  capacity: '6',
  price: '80.00',
  id: 123,
};

export const hours = [
  '1',
  '2',
  '3',
  '4',
  '5',
  '6',
  '7',
  '8',
  '9',
  '10',
  '11',
  '12',
];
export const minutes = [
  '00',
  '5',
  '10',
  '15',
  '20',
  '25',
  '30',
  '35',
  '40',
  '45',
  '50',
  '55',
];
export const periods = ['AM', 'PM'];

export const carDetails = {
  carImage: '/img/darkcar.png',
  smallCar: '/img/darkcarsm.svg',
  view1: '/img/view1.png',
  view2: '/img/view2.png',
  title: 'Nissan GT - R',
  description:
    'NISMO has become the embodiment of Nissans outstanding performance, inspired by the most unforgiving proving ground, the race track.',
  type: 'Sport',
  capacity: '2 Person',
  transmission: 'Manual',
  gasoline: '70',
  price: '$80.00',
  id: 124,
};

export const carArray = [
  {
    title: 'Honda Civic',
    vehicleType: 'Sedan',
    gallons: 12,
    image: '/img/car.png',
    transmission: 'Automatic',
    capacity: 5,
    price: 220,
    id: 125,
  },
  {
    title: 'Chevrolet Silverado',
    vehicleType: 'Truck',
    gallons: 20,
    image: '/img/car.png',
    transmission: 'Automatic',
    capacity: 4,
    price: 380,
    id: 126,
  },
  {
    title: 'BMW X5',
    vehicleType: 'SUV',
    gallons: 16,
    image: '/img/car.png',
    transmission: 'Automatic',
    capacity: 5,
    price: 550,
    id: 127,
  },
  {
    title: 'Ford Mustang',
    vehicleType: 'Sports Car',
    gallons: 10,
    image: '/img/car.png',
    transmission: 'Manual',
    capacity: 2,
    price: 400,
    id: 128,
  },
  {
    title: 'Nissan Leaf',
    vehicleType: 'Electric',
    gallons: 0,
    image: '/img/car.png',
    transmission: 'Automatic',
    capacity: 5,
    price: 320,
    id: 129,
  },
  {
    title: 'Jeep Wrangler',
    vehicleType: 'SUV',
    gallons: 15,
    image: '/img/car.png',
    transmission: 'Manual',
    capacity: 4,
    price: 330,
    id: 130,
  },
  {
    title: 'Audi A4',
    vehicleType: 'Sedan',
    gallons: 14,
    image: '/img/car.png',
    transmission: 'Automatic',
    capacity: 5,
    price: 420,
    id: 131,
  },
  {
    title: 'Lexus RX',
    vehicleType: 'SUV',
    gallons: 17,
    image: '/img/car.png',
    transmission: 'Automatic',
    capacity: 5,
    price: 500,
    id: 132,
  },
  {
    title: 'Ford Escape',
    vehicleType: 'SUV',
    gallons: 15,
    image: '/img/car.png',
    transmission: 'Automatic',
    capacity: 5,
    price: 270,
    id: 133,
  },
  {
    title: 'Subaru Outback',
    vehicleType: 'SUV',
    gallons: 14,
    image: '/img/car.png',
    transmission: 'Automatic',
    capacity: 5,
    price: 280,
    id: 134,
  },
  {
    title: 'Chevrolet Corvette',
    vehicleType: 'Sports Car',
    gallons: 11,
    image: '/img/car.png',
    transmission: 'Manual',
    capacity: 2,
    price: 650,
    id: 135,
  },
  {
    title: 'Hyundai Sonata',
    vehicleType: 'Sedan',
    gallons: 13,
    image: '/img/car.png',
    transmission: 'Automatic',
    capacity: 5,
    price: 230,
    id: 136,
  },
  {
    title: 'GMC Sierra',
    vehicleType: 'Truck',
    gallons: 19,
    image: '/img/car.png',
    transmission: 'Automatic',
    capacity: 3,
    price: 400,
    id: 137,
  },
  {
    title: 'Volkswagen Golf',
    vehicleType: 'Hatchback',
    gallons: 12,
    image: '/img/car.png',
    transmission: 'Automatic',
    capacity: 5,
    price: 210,
    id: 138,
  },
];
