export const carCard = {
  title: 'CR-V',
  vehicleType: 'SUV',
  gallons: '80L',
  image: '/img/car.png',
  transmission: 'Manual',
  capacity: '6 People',
  price: '$80.00/',
};

export const hours = [
  '1',
  '2',
  '3',
  '4',
  '5',
  '6',
  '7',
  '8',
  '9',
  '10',
  '11',
  '12',
];
export const minutes = [
  '00',
  '5',
  '10',
  '15',
  '20',
  '25',
  '30',
  '35',
  '40',
  '45',
  '50',
  '55',
];
export const periods = ['AM', 'PM'];

export const carArray = [
  {
    title: 'Honda Civic',
    vehicleType: 'Sedan',
    gallons: 12,
    image: '/img/car.png',
    transmission: 'Automatic',
    capacity: 5,
    price: 220,
  },
  {
    title: 'Chevrolet Silverado',
    vehicleType: 'Truck',
    gallons: 20,
    image: '/img/car.png',
    transmission: 'Automatic',
    capacity: 4,
    price: 380,
  },
  {
    title: 'BMW X5',
    vehicleType: 'SUV',
    gallons: 16,
    image: '/img/car.png',
    transmission: 'Automatic',
    capacity: 5,
    price: 550,
  },
  {
    title: 'Ford Mustang',
    vehicleType: 'Sports Car',
    gallons: 10,
    image: '/img/car.png',
    transmission: 'Manual',
    capacity: 2,
    price: 400,
  },
  {
    title: 'Nissan Leaf',
    vehicleType: 'Electric',
    gallons: 0,
    image: '/img/car.png',
    transmission: 'Automatic',
    capacity: 5,
    price: 320,
  },
  {
    title: 'Jeep Wrangler',
    vehicleType: 'SUV',
    gallons: 15,
    image: '/img/car.png',
    transmission: 'Manual',
    capacity: 4,
    price: 330,
  },
  {
    title: 'Audi A4',
    vehicleType: 'Sedan',
    gallons: 14,
    image: '/img/car.png',
    transmission: 'Automatic',
    capacity: 5,
    price: 420,
  },
  {
    title: 'Lexus RX',
    vehicleType: 'SUV',
    gallons: 17,
    image: '/img/car.png',
    transmission: 'Automatic',
    capacity: 5,
    price: 500,
  },
  {
    title: 'Ford Escape',
    vehicleType: 'SUV',
    gallons: 15,
    image: '/img/car.png',
    transmission: 'Automatic',
    capacity: 5,
    price: 270,
  },
  {
    title: 'Subaru Outback',
    vehicleType: 'SUV',
    gallons: 14,
    image: '/img/car.png',
    transmission: 'Automatic',
    capacity: 5,
    price: 280,
  },
  {
    title: 'Chevrolet Corvette',
    vehicleType: 'Sports Car',
    gallons: 11,
    image: '/img/car.png',
    transmission: 'Manual',
    capacity: 2,
    price: 650,
  },
  {
    title: 'Hyundai Sonata',
    vehicleType: 'Sedan',
    gallons: 13,
    image: '/img/car.png',
    transmission: 'Automatic',
    capacity: 5,
    price: 230,
  },
  {
    title: 'GMC Sierra',
    vehicleType: 'Truck',
    gallons: 19,
    image: '/img/car.png',
    transmission: 'Automatic',
    capacity: 3,
    price: 400,
  },
  {
    title: 'Volkswagen Golf',
    vehicleType: 'Hatchback',
    gallons: 12,
    image: '/img/car.png',
    transmission: 'Automatic',
    capacity: 5,
    price: 210,
  },
];
